### ISSUE TITLE
Add a feature to check for changes

### ISSUE THREAD

**Issue by robinsm** [pbs/pbs-media-manager-craft-plugin#12]
The video goes into more detail here and we'd have to carefully thing about how to implement this and talks about doing a better job of cleaning up what assets are available.

The earlier part of the video discusses the scheduling of a sync operation and has been left in for context.

https://user-images.githubusercontent.com/4096355/234790395-9c5b6fd5-08c1-49a2-84ee-7b7255f7117a.mp4

Full length video [here](https://drive.google.com/drive/u/3/folders/1nuXXTIFETjCVYrPWRBsPlPAZi3F6wxXz)

**Comment by andrewmenich** [comment]
Clarifying that "check for changes" is referring to removing media items that have been unpublished in the console during a sync. Similar to Feed Me's "Delete items not in feed" option.

**Comment by andrewmenich** [comment]
Other issues mentioned in the video include: 
- Season meta not syncing to the media entry
- Media entries from all shows/sites appear when adding media for a specific show

**Comment by smaylath** [comment]
Notes from huddle: https://docs.google.com/document/d/1SfLybD4bluffDw-XvAF_6UEooL5aXGGzPzE9scqclds/edit

**Comment by smaylath** [comment]
Recapping notes from status convo with Andrew:

Procedure Overview for GA / KB:
- Click update
- allow processing time
- allow queue Running time
- Manage stale media and manually remove/disable the related entries

Partial reason for processing time: 
- initial api data dump happens
- it's built to double check via looping 1 by 1 through media
this is due to the multisite setup and initial plugin build, so there are lots of "false positives" for show entries in the wrong show multisite instances

**Comment by smaylath** [comment]
Next step: GW to connect about deployment readiness to General Audiences develop environment
@andrewmenich @robinsm

**Comment by smaylath** [comment]
Deployed to GA Develop - looking into server error message

**Comment by smaylath** [comment]
@SamLaneyPBS this is review-ready on GA develop: https://develop-gacraft.console.pbs.org/admin/mediamanager/stale-media

### A quick overview of how this will work:

There is a new section under MM called Manage Stale Media (this can be renamed if you prefer)
<img width="1285" alt="Screenshot 2023-07-13 at 16 30 02" src="https://github.com/pbs/pbs-media-manager-craft-plugin/assets/77697559/86450498-3f5d-4d94-8232-f343f9598652">



- After clicking to run a sync
- Allow processing time for the sync itself
- Allow queue running time (this is for a series of loops double checking for duplicate content due to multisite)
- Manage stale media and manually remove/disable the related entries as you would like

------

### For testing: 

Andrew only synced _Call the Midwife_, so we encourage you to sync other shows to see what other entries are marked for deletion. 
We'll definitely lean on your knowledge of the content to thoroughly test and make sure the stale media section is behaving correctly and pulling up the expected entries. 
If you find a way to break it, just let us know! Steps to recreate and specific links or screenshots will be super helpful for us to troubleshoot if you encounter questions. 

Just give @andrewmenich or I a shout if you have questions! He'll be away for a few days, so no rush to test this immediately.

**Comment by SamLaneyPBS** [comment]
Hey @andrewmenich, I believe this is working pretty well. I've synced the Film Festival assets and saw one of the older assets was added to the list - and its status met our criteria. 

Upon re-syncing, however, a flood of "disabled" assets that I had deleted were created as Media entries. So while I think this "stale media" process is working correctly, we may need to also adjust what assets get synced (and created as Media entries) in order to accomplish the broader goal: reduce the amount of unusable/unsuitable assets a producer sees when trying to find video. 

![image](https://github.com/pbs/pbs-media-manager-craft-plugin/assets/129447081/57f91b24-fd94-4e41-ade5-ba70ac55b5b4)

**Comment by SamLaneyPBS** [comment]
Hi Andrew - thanks for explaining all that. Is there an opportunity to do a check to see if availability of an asset is in the past or the future? There may be a use case where an asset will come live in the coming days, so we'd want to sync it ahead of time. 

If not, then I think it would be worth making the change as you describe - that use case is borderline an edge case.

**Comment by andrewmenich** [comment]
Yeah, we can check for that. So as long as the availability end date is in the past and the availability start date is not in the future, it should be ignored / not added as an entry in Craft?

**Comment by SamLaneyPBS** [comment]
Yes, that would be perfect!

**Comment by andrewmenich** [comment]
@SamLaneyPBS I've made this adjustment and redeployed to GA Develop. Please have another look and let me know if this behaves better for you. Thanks!

**Comment by SamLaneyPBS** [comment]
@andrewmenich It looks like it's correctly not syncing assets that are expired and have availabilities set in the past. However, I synced Call the Midwife, and assets with availability set in the future don't seem to appear/sync. Specifically, there should be 8 episodes that sync because their availability is set for September 3 (screenshot attached)

![image](https://github.com/pbs/pbs-media-manager-craft-plugin/assets/129447081/f0e4797f-b1f9-4c69-bfd8-d4643bfdd127)

**Comment by andrewmenich** [comment]
Hi @SamLaneyPBS 

I believe that asset is in the system here: https://develop-gacraft.console.pbs.org/admin/entries/media/22220-episode-1?site=callTheMidwife#tab--api

How were you searching for it? I'm thinking that's something we could address while I'm in there if it's a quick fix. I noticed that the slug for the media entries in Craft are being derived from the title instead of the slug that is sent from the API, in this case it would be `call-the-midwife-season-12-episode-1-full-episode` instead of `episode-1`

**Comment by smaylath** [comment]
Hi @andrewmenich and @SamLaneyPBS! Looping around here after our retainer planning call to confirm we're good with launching this to production. 

I had snagged time on Andrew's Tuesday calendar for this, but wasn't sure of @crzbarcea 's availability due to her travel schedule. So, we have a little flexibility on our side to work on this deployment between Tues&Thurs this week. 

Thank you!

**Comment by akatgw** [comment]
@SamLaneyPBS @crzbarcea Hi there - I just wanted to check on the status and launch plan for this? We're on standby but would need to get it done by tomorrow for this week. Thank you!

**Comment by andrewmenich** [comment]
Thanks for the information - that makes sense. So this is what I see in the API response: 
<img width="466" alt="image" src="https://github.com/pbs/pbs-media-manager-craft-plugin/assets/29585821/3c3daf2d-870d-447b-aa6a-b689a78f3a35">

Based on this data, if `start` is `null` for public availability, does that mean it should be considered as no longer available? Thanks!

**Comment by SamLaneyPBS** [comment]
So "public" could be "null" but "all members" could have a date. If both "public" and "all_members" have a null, let's remove!

**Comment by andrewmenich** [comment]
I've updated Media Manager and GA preprod to reflect this change. I ran a sync of Film Festival and it seems the trailers for 2012-2016 have been marked for deletion.  Let me know if anything else is amiss!

**Comment by SamLaneyPBS** [comment]
looks good! i think we can deploy

**Comment by akatgw** [comment]
Thanks @SamLaneyPBS - I'll huddle with Andrew on next steps for this so we can get it done early next week.

**Comment by akatgw** [comment]
Hi @crzbarcea - I confirmed with Andrew that we're all set on our end. Let us know if you need any assistance during launch!

**Comment by smaylath** [comment]
@crzbarcea hello there! doing a bit of cross checking - did this get deployed to production? Thank you!

**Comment by smaylath** [comment]
deployed to preprod & prod & completed 12.14.23
