### ISSUE TITLE
Ability for Author to use filters in "Select Entry" View

### ISSUE THREAD

**Issue by smaylath** [pbs/pbs-media-manager-craft-plugin#15]
- This is currently broken
- Andrew suspects it’s an issue with the UpVote plugin
- Sam mentioned a feature he’d like to have is where you can do show-specific filtering vs. being shown a laundry list. Fixing the filter mentioned above is a step in the right direction, but he might want something even more specific.

**Comment by andrewmenich** [comment]
This issue is specific to the PBS Foods instance and unrelated to Media Manager. 

To address the larger issue of show-specific filtering, I think the element filtering options introduced in Craft 4 will achieve what Sam is looking for without making any changes to Media Manager. For Craft 3 sites, using the Search bar with a specific field handle and value should properly filter the results. I've attached some screenshots of what that looks like. The 'Site' on the left that says 'Call the Midwife' is sort of irrelevant here because all Media entries propagate to all Sites, so it shouldn't matter what Site is selected.

![SCR-20230926-irxs](https://github.com/pbs/pbs-media-manager-craft-plugin/assets/29585821/b5db9c26-10e2-498b-bcf5-caa22b2ae779)
![SCR-20230926-irvi](https://github.com/pbs/pbs-media-manager-craft-plugin/assets/29585821/339ee2d1-4066-4a37-8a3d-661a1a87b96f)

**Comment by smaylath** [comment]
@andrewmenich before I closed this out, just checking that this issue remains PBS Foods related? With all the MM updates, wanted to be sure.

**Comment by andrewmenich** [comment]
@smaylath Yes, all the above info still stands and is not really a Media Manager issue. The Upvote plugin on the Foods site was causing bad requests when trying to use Craft 4's native entry filtering feature so that might need to looked into independently. 

@SamLaneyPBS just pinging you to make sure you've seen the screenshots above on how you can filter Media entries to a specific show.

**Comment by smaylath** [comment]
Thank you @andrewmenich! I'll go ahead and close this for now. We can share this ticket with the Foods team if it's useful to reference in the future.

**Comment by SamLaneyPBS** [comment]
Thanks Andrew, I was aware of how to filter using [show name]: queries in Craft 3. I think the goal of my request was to do something more user friendly than that type of filter search. If Craft 4 does a better job of this, perhaps we can revisit once GA Craft and KB Craft are updated to version 4.
